### ISSUE TITLE
Installer adjustment

### ISSUE THREAD

**Issue by nemke82** [djfordz/cpanel_whitelist_plugin#1]
Hello,

Please adjust the 33rd line of install.sh script and change,

from:
users="$(awk -F: '($3 >= 1000) { print $1}' /etc/passwd)"

to:
users="$(find /var/cpanel/users -type f|awk -F / '{print $5}')"

**Comment by djfordz** [comment]
changed install.sh not to change permissions on files.
changed script to set euid to script owner instead.
pushed changes
need to test.
